### ISSUE TITLE
Add Jump Badge

### ISSUE THREAD

**Issue by GKellen** [fremenusul/DPRIS#23]
we dont have jump badge

**Comment by fremenusul** [comment]
You sure? I see a jump badge

**Comment by fremenusul** [comment]
3rd row 
![screen shot 2017-05-29 at 10 41 44 pm](https://cloud.githubusercontent.com/assets/5619884/26569523/017fe8bc-44c0-11e7-8203-3614c6d8b3a5.png)

**Comment by GKellen** [comment]
Then im missing something. Ill have to look.

**Comment by GKellen** [comment]
Its the Free Fall Badge. Ill add it in this week.

**Comment by fremenusul** [comment]
O.o... Didn't even know about that one.

**Comment by GKellen** [comment]
added to the folder

**Comment by GKellen** [comment]
Can you add in the action to put this badge on their character
